config/routes.rb
Rails.application.routes.draw do
  get 'findclients/:client', to: 'invoices#index', as: :findclient
  resources :charges

  get    "invoices/preview/:id",      to: "invoices#preview", as: :preview
  get    "invoices/create_payment/:id",      to: "invoices#create_payment", as: :create_payment
  get    "invoices/new_payment/:id",      to: "invoices#new_payment", as: :new_payment

  resources :labels
  resources :clients
  resources :invoices do
    resources :invoicelines
  end
  resources :materials do
    resources :material_comments
  end
  resources :filters
  resources :folders do
    resources :documents
  end
  devise_for :users
  root to: 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :invoicelines, dependent: :destroy
  belongs_to :client, optional: true
    def self.search(search)
    if search
      where("name ILIKE ?",  "%#{search}%")
    else
      all
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit,:preview, :update, :destroy, :create_payment, :new_payment]
  before_action :authenticate_user!, :except => [:preview]
  helper_method :compute_invoice
  helper_method :invoice_number




  # GET /invoices
  # GET /invoices.json
  def index
    @clients = Client.all
    @invoices = Invoice.search(params[:search])
    @Invoices = Invoice.order(:name)
    @invoices = @invoices.page(params[:page] || 1)
    @invoicelines = Invoiceline.all
    respond_to do |format|
    format.html  # index.html.erb
    format.json  { render :json => @clients.map(&:name) }
    @invoicelines = Invoiceline.all


  end
end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
        @user = current_user

    @invoiceline = Invoiceline.new
    @invoices = Invoice.all
    @invoicelines = Invoiceline.all
    @sum = self.compute_invoice(@invoice)

  end

  def compute_invoice(invoice)
    @sum = 0
    @invoice = invoice
    @invoicelines = Invoiceline.all
    @total = @invoicelines.where(:invoice_id => @invoice.id).each do |invoicelin|
      if invoicelin.price.present?
        price =   invoicelin.price.to_i
      elsif invoicelin.label.present?
        price =  invoicelin.label.price.to_i
      else
        price = 0
      end
      @sum += (invoicelin.quantity.to_i*invoicelin.price.to_i)
    end
    return @sum
  end

  def invoice_number(invoice)
    @number = ''
    @invoice = invoice
    @id = @invoice.id.to_s
    @date =  (Date.today.strftime("%Y")+'-'+Date.today.strftime("%m")).to_s
    @number = @date +'-'+ @id
    return @number
  end

  def preview
    @invoiceline = Invoiceline.new
    @invoices = Invoice.all
    @invoicelines = Invoiceline.all
    @sum = 0
    @user = current_user
    @total = @invoicelines.where(:invoice_id => @invoice.id).each do |invoicelin|
      @invoicelin = invoicelin
      if invoicelin.price.present?
        price =   invoicelin.price.to_i
      elsif invoicelin.label.present?
        price =  invoicelin.label.price.to_i
      else
        price = 0
      end
      quantity = invoicelin.quantity.to_i
      @sum+= quantity*price
      @sumttc= @sum*1.20
    end
    respond_to do |format|
      format.html
      format.pdf do
        render  pdf: 'invoice', template: 'invoices/invoice',
        page_size: 'A4',
        encoding:"UTF-8"
      end # Excluding ".pdf" extension.
    end
    @amount2 = @sumttc
    @amount = @sumttc*100
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.status = "Crée"
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to edit_invoice_path(@invoice), notice: 'Devis cree.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET /invoices/1/edit
  def edit
    @user = current_user
    @sum = 0
    @clients = Client.all
    @invoiceline = Invoiceline.new
    @invoicelines = Invoiceline.all
      if @clients.where(id: @invoice.client_id).exists?
        @client = @clients.find(@invoice.client_id)
      end
    @clientnew = Client.new
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Devis cree.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to edit_invoice_path(@invoice), notice: 'Devis modifie.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Devis supprime.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:author, :status, :days, :invoicetype, :name, :email,:client_id)
    end
  end

app/views/invoices/_form.html.erb
<div class="invoice-container">
  <div class="invoice-filler">



    <div class="top">
      <%= image_tag ('https://media-exp1.licdn.com/dms/image/C4E0BAQFPOivHFXWqYw/company-logo_200_200/0/1521810001068?e=2159024400&v=beta&t=Rn_Td_0xCBZ2drU639qU9cbJTbf_oASXBBoIpnhQ19w') %>
      <div>FACTURE N° <%= invoice_number(@invoice) %></div>
    </div>


 <div class="client">
  <%= simple_form_for(@invoice) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <%= f.association :client, label: false, include_blank: "Client" %>
      <div class="action">
       <button type="button" class="btn btn-flat-form" data-toggle="modal" data-target="#create">
          Ajouter
        </button>
        <%= f.button :submit, "Valider", class: "btn btn-flat-form" %>
      </div>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="create" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Ajouter un client</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            <%= simple_form_for  @clientnew do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                         <div class="form-inputs">
                <%= f.input :lastinvoice, :as => :hidden, :input_html => { value: @invoice.id } %>
                <%= f.input :name, label: false, placeholder: "Nom de l'entreprise" %>
                <%= f.input :address, label: false, placeholder: "Adresse" %>
                <%= f.input :leader,  label: false, placeholder: "Nom du destinaire" %>
                <%= f.input :email, label: false, placeholder: "Email du client" %>
              </div>

              <div class="modal-footer">
                <%= f.button :submit, "Soumettre", class: "btn btn-flat" %>
            <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <br/>
      <% if @client.present? %>
        <b><%= @client.name  %></b>
         <br/><%= @client.leader  %>
          <br/><%= @client.address  %>
        <% else %>
        <b>Nom de la société</b>
 <br/>Nom du destinaire
      <br/>Addresse
      <% end %>

      <% if @client.present? %>
      <div class="action">
       <button type="button" class="btn btn-flat-form" data-toggle="modal" data-target="#edit">
          Modifier
        </button>
              <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modifier le client</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            <%= simple_form_for(@client) do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                         <div class="form-inputs">
                <%= f.input :name, label: false, placeholder: "Nom de l'entreprise" %>
                <%= f.input  :address, label: false, placeholder: "Adresse" %>
                <%= f.input :leader,  label: false, placeholder: "Nom du destinaire" %>
                <%= f.input :email, label: false, placeholder: "Email du client" %>
              </div>

              <div class="modal-footer">
                <%= f.button :submit, "Soumettre", class: "btn btn-flat" %>
            <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
       <% end %>

      </div>

      <br/><br/>
                <table class="table invoiceline">
                  <thead>
                    <tr>
                       <th style="width: 33%"><b>Libellé</b></th>
                        <th style="width: 5%"><b>Qté</b></th>
                        <th style="width: 10%"><b>Prix</b></th>
                        <th style="width: 10%"><b>Total HT</b></th>
                        <th style="width: 10%"><b>TVA</b></th>
                        <th style="width: 10%"><b>Total TTC</b></th>
                        <th style="width: 10%"><b>Action</b></th>
                    </tr>
                  </thead>
                  <tbody>
    <tr>
                <%= simple_form_for [@invoice, @invoiceline] do |f| %>
                    <td scope="col-6">
                      <%= f.input :name, label: false %>
                    </td>
                    <td>
                      <%= f.input :quantity, label: false  %>
                    </td>
                    <td>
                      <%= f.input :price, label: false %>

                      </td>
                   <td>

                  </td>
                   <td>
                  <%= f.input :label_id, collection: ['20%', '10%', '0'], default: '20%', label: false %>

                  </td>
                   <td>

                  </td>
                  <td>
                    <%= f.submit "+", class: "btn btn-flat-form"%>
                  </td>
                  <% end %>
    </tr>
   <% @invoice.invoicelines.each do |invoiceline| %>
      <tr>

        <td>
          <% if invoiceline.name.present? %>
          <%= invoiceline.name %>
          <% else %>
          <% end %>
        </td>

        <td><%= invoiceline.quantity %></td>
        <td>
          <% if invoiceline.price.present? %>
          <%= invoiceline.price %> €
          <% else %>
          Saisir un tarif
          <% end %>
        </td>
          <td>

          <%= (invoiceline.price.to_i)*(invoiceline.quantity.to_i) %>  €

        </td>
        <td>

          <%= invoiceline.label_id.to_i %> %

        </td>
        <td>
          <%= (invoiceline.price.to_i)*(invoiceline.quantity.to_i)*(1+(invoiceline.label_id.to_i*0.01)) %>  €
        </td>

        <td>
          <p><%= link_to 'x', invoice_invoiceline_path(@invoice, invoiceline), method: :delete, data: { confirm: 'Etes vous certain?' }, class: "btn btn-flat-form" %>
          </p>
        </td>
     </tr>

      <% end %>

  </tbody>
</table>

    <div class="table-invoice">
      <div class="table-invoice-line">
        <div class="col-2"><b>Total HT:</b></div>
        <div class="col-2"><%= compute_invoice(invoice).round(2) %>€
 </div>

      </div>
    </div>
    <div class="table-invoice">
      <div class="table-invoice-line">
        <div class="col-2"><b>Total TTC:</b></div>
        <div class="col-2"><%= (compute_invoice(invoice).round(2)*(1.2))  %> €</div>

      </div>
    </div>

      <div class="date">
        <p>          <%= simple_form_for(@invoice) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <%= f.input :days, label: 'Echéance', collection: ['30 jours', '45 jours'], default: '30jours' %>
      <div class="action">
        <%= f.button :submit, "Valider", class: "btn btn-flat-form" %>
      </div>
      <% end %></p>

<p>Crée le: <%= @invoice.created_at.strftime('%d/%m/%y ')  %>
<br/>Echéanche: <%= (@invoice.created_at + @invoice.days.to_i.days).strftime('%d/%m/%y ') %> </p>

      </div>
      </div>






<div class="right">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
                  <a href="#" class= "nav-link ">Envoyer</a>
      </li>
      <li class="nav-item">
                  <a href="#" class= "nav-link">Relancer</a>
      </li>
         <li class="nav-item">
                  <%= link_to 'Voir', invoice_path, class: "nav-link" %>
      </li>
             <li class="nav-item">
                  <%= link_to 'Télécharger', preview_path(invoice, format: 'pdf'),  download: true,class: "nav-link" %>
      </li>
         <li class="nav-item">
                <%= link_to 'Supprimer', invoice, method: :delete, data: { confirm: 'Etes vous certain?' }, class: "nav-link" %>
      </li>

    </ul>
  </div>
</nav>
<br/>
<b>Information sur la facture</b><br/><br/>
<p>Destinataire:<% if @client.present? %>
        <%= @client.email  %>
     <% end %> </p>
<p>Crée le: <%= @invoice.created_at.strftime('%y/%m/%y ')  %></p>
<p>Echéanche: <%= (@invoice.created_at + @invoice.days.to_i.days).strftime('%d/%m/%y ') %> </p>
<p>Statut: <span class="badge badge-primary"><%= invoice.status %></span></p>


<b>Information sur l'entreprise </b><br/><br/>
<p>Adresse: <%= @user.address  %></p>
<p>Banque: <%= @user.bank  %></p>
<p>RIB: <%= @user.bank  %></p>
<p>Siret: <%= @user.siret  %></p>
<p><%= link_to 'Modifier',edit_user_registration_path, class: "btn btn-flat" %>
</p>

</div>




  </div>


</div>

app/views/invoices/_payment.html.erb
  <h4 class="subtitle is-4">Payment</h4>

  <div class="notification is-light has-text-centered">
    <i class="fa fa-credit-card"></i>
    All jobs cost <strong>$300</strong> USD for 30 days.
    <span class="block mb4"></span>
  </div>

  <div class="form-row">
    <label for="card-element" class="label">
      Enter credit or debit card
    </label>

    <div id="card-element" class="form-control">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- used to display Element errors -->
    <div id="card-errors" role="alert"></div>
  </div>

app/views/invoices/create_payment.html.erb
<h2>Merci, le paiement de <strong>  <%= @amount2 %>
</strong>a ete effectue!</h2>

app/views/invoices/edit.html.erb
<div class="header">
  <div class="action">
    <h2>Nouvelle facture</h2>
    <div></div>
  </div>
</div>
  <%= render 'form', invoice: @invoice %>

app/views/invoices/index.html.erb
<div class="header">
  <div class="action">
  <h2>Vos factures</h2>
  <%= link_to 'Nouvelle Facture', new_invoice_path, class: "btn btn-flat" %>
  </div>
</div>

<div class="container-list">
  <div class="left-container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Facture N°</th>
          <th scope="col">Client</th>
          <th scope="col">Montant</th>
          <th scope="col">Statut</th>
        </tr>
      </thead>
      <tbody>
        <% @invoices.each do |invoice| %>
          <tr class="tablinks " onclick="openCity(event, '<%= invoice.id %>')" id="defaultOpen">
            <td><%= invoice_number(invoice) %></td>
            <td>
              <%= @clients.find(invoice.client_id).name if @clients.where(id: invoice.client_id).exists? %>
            </td>
            <td><%= compute_invoice(invoice) %>€</td>
            <td>
              <span class="badge badge-primary"><%= invoice.status %></span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="right-container">
    <% @invoices.each do |invoice| %>
      <div id="<%= invoice.id %>" class="tabcontent">

        <div class="content">
          <div class="top">
            <div>
         <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
                  <a href="#" class= "nav-link ">Envoyer</a>
      </li>
      <li class="nav-item">
                <%= link_to 'Modifier', edit_invoice_path(invoice), class: "nav-link" %>
      </li>
         <li class="nav-item">
                  <%= link_to 'Voir', invoice_path(invoice), class: "nav-link" %>
      </li>
             <li class="nav-item">
                  <%= link_to 'Télécharger', preview_path(invoice, format: 'pdf'),  download: true,class: "nav-link" %>
      </li>
         <li class="nav-item">
                <%= link_to 'Supprimer', invoice, method: :delete, data: { confirm: 'Etes vous certain?' }, class: "nav-link" %>
      </li>

    </ul>
  </div>
</nav>
            </div>
                        <p>     FACTURE N°<%= invoice_number(invoice) %></p>

          </div>

          <p>
                <div class="table-invoice">
      <div class="table-invoice-line">

        <div class="col-6"><b>Libellé</b></div>
        <div class="col-1"><b>Qté</b></div>
        <div class="col-3"><b>Prix</b></div>

      </div>
    </div>
                <div class="table-invoice">
      <% invoice.invoicelines.each do |invoiceline| %>
      <div class="table-invoice-line">

        <div class="col-6">
          <% if invoiceline.name.present? %>
          <%= invoiceline.name %>
          <% else %>
          <%= invoiceline.label.name %>
          <% end %>
        </div>

        <div class="col-1"><%= invoiceline.quantity%></div>
        <div class="col-3">
          <% if invoiceline.price.present? %>
          <%= invoiceline.price %> €
          <% elsif invoiceline.label.present? && invoiceline.label.price != nil %>
          <%= invoiceline.label.price %>€
          <% elsif invoiceline.label.price == nil && invoiceline.label.price == 0 %>
          Saisir un tarif
          <% else %>
          Saisir un tarif
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
        <div class="table-invoice">
      <div class="table-invoice-line">
        <div class="col-1"><b>HT</b></div>
        <div class="col-3"><%= compute_invoice(invoice).round(2) %> €</div>

      </div>

      <div class="table-invoice-line">
        <div class="col-1"><b>TVA</b></div>
        <div class="col-3"><%= (compute_invoice(invoice)*1.2 - compute_invoice(invoice)).round(2) %> €</div>

      </div>
    </div>
        <div class="table-invoice">

      <div class="table-invoice-line">
        <div class="col-1"><b>TTC</b></div>
        <div class="col-3"><%= compute_invoice(invoice)*1.2.round(2) %> €</div>

      </div>
    </div>

          </p>
        </div>
              <div class="bottom">
      <div>
        <p>Client: <%= @clients.find(invoice.client_id).name if @clients.where(id: invoice.client_id).exists? %></p>
        <p>Nom: <%= @clients.find(invoice.client_id).leader if @clients.where(id: invoice.client_id).exists? %></p>
        <p>Adresse: <%= @clients.find(invoice.client_id).address if @clients.where(id: invoice.client_id).exists? %></p>
      </div>
      <div>
        <p>Créé le: 31/12/2020</p>
        <p>Échéance: 31/01/2021 </p>
      </div>

    </div>
      </div>


    <% end %>



  </div>
</div>


<script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>

app/views/invoices/new.html.erb
<div class="header">
  <div class="action">
    <h2>Nouvelle facture</h2>
    <div></div>
  </div>
</div>
<%= render 'form', invoice: @invoice %>

app/views/invoices/new_payment.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Total:<%= @amount2 %> euros </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Payer le devis"
          data-amount="<%= @amount %>" class="btn btn-flat"
          data-locale="auto"></script>
<% end %>

app/views/invoices/preview.html.erb
  <% if user_signed_in? %>

  <% else %>

  <div class="navbar">
    <div><%= image_tag ("logo.png") , class: "navbar-brand logoinvoice" %></div>
    <div>    <h2>  <b>Devis: </b>  <%= @invoice.name if @invoice.name.present?  %></h2>
    </div>
  </div>
  <% end %>

  <div class="container-list">

    <%= link_to 'Télécharger au format PDF', preview_path(@invoice, format: 'pdf'), class: "btn-flat btn"  %>
    <div class="spacer"></div>
    <div class="row">
      <div class="commentbox col-sm-2">
        <p>
          <strong>Auteur:</strong>
          <%= @invoice.author if @invoice.author.present?  %>
        </p>

        <p>
          <strong>Status:</strong>
          <%= @invoice.status if @invoice.status.present?%>
        </p>

        <p>
          <strong>Type:</strong>
          <%= @invoice.invoicetype if @invoice.invoicetype.present?  %>
        </p>

        <p>
          <strong>Client:</strong>
          <%= @invoice.client.name if @invoice.client.name.present? %>
        </p>
      </div>


      <div class="spacer"></div>

      <div class="col-sm-9">

        <div class="table-invoice">
          <div class="table-invoice-line">

            <div class="col-6"><b>Libellé</b></div>
            <div class="col-2"><b>Qté</b></div>
            <div class="col-2"><b>Prix</b></div>

          </div>
        </div>

        <div class="table-invoice">
          <% @invoice.invoicelines.each do |invoiceline| %>
          <div class="table-invoice-line">

            <div class="col-6">
              <% if invoiceline.name.present? %>
              <%= invoiceline.name %>
              <% else %>
              <%= invoiceline.label.name %>
              <% end %>
            </div>

            <div class="col-2"><%= invoiceline.quantity%></div>
            <div class="col-2">
              <% if invoiceline.price.present? %>
              <%= invoiceline.price %> €
              <% elsif invoiceline.label.present? && invoiceline.label.price != nil %>
              <%= invoiceline.label.price %> €
              <% elsif invoiceline.label.price == nil && invoiceline.label.price == 0 %>
              Probleme devis
              <% else %>
              Probleme devis
              <% end %>
            </div>
          </div>

          <% end %>
        </div>
        <div class="table-invoice">
          <div class="table-invoice-line">
            <div class="col-1"><b>Total HT:</b></div>
            <div class="col-2"><%= @sum %> €</div>

          </div>
        </div>
        <div class="table-invoice">
          <div class="table-invoice-line">
            <div class="col-1"><b>Total TTC:</b></div>
            <div class="col-2"><%= @sumttc %> €
              <% if @invoice.status === "paiement effectué" %>
              Devis payé
              <% else %>

              <%= form_tag charges_path do %>
              <input type="hidden" name="invoice_id" value='<%= @invoice.id %>'>

              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button cta"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Payer le devis"
              data-amount="<%= @amount.to_i %>"
              data-locale="auto" data-currency="eur" data-label="Payer le devis">

            </script>


            <% end %>
            <% end %>
          </div>

        </div>
      </div>














    </div>
  </div>
</div>

app/views/invoices/show.html.erb
<div class="header">
  <div class="action">
  <h2>Vos factures</h2>
  <%= link_to 'Nouvelle Facture', new_invoice_path, class: "btn btn-flat" %>
  </div>
</div>


<div class="container-show">
  <div class="left-container">
    <iframe src=" https://rise-poc.herokuapp.com/invoices/preview/<%= @invoice.id %>.pdf" width="600" height="780" style="border: none;"> </iframe>
  </div>


  <div class="right-container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
                  <a href="#" class= "nav-link ">Envoyer</a>
      </li>
      <li class="nav-item">
                  <a href="#" class= "nav-link">Relancer</a>
      </li>

         <li class="nav-item">
                  <%= link_to 'Voir', invoice_path, class: "nav-link" %>
      </li>
                   <li class="nav-item">
                  <%= link_to 'Télécharger', preview_path(@invoice, format: 'pdf'),  download: true, class: "nav-link" %>
      </li>
         <li class="nav-item">
                <%= link_to 'Supprimer', @invoice, method: :delete, data: { confirm: 'Etes vous certain?' }, class: "nav-link" %>
      </li>

    </ul>
  </div>
</nav>
<br/>
<b>Information sur la facture</b><br/><br/>
<p>Destinataire:<% if @client.present? %>
        <%= @client.email  %>
     <% end %> </p>
<p>Crée le: <%= @invoice.created_at.strftime('%y/%m/%y ')  %></p>
<p>Echéanche: <%= (@invoice.created_at + @invoice.days.to_i.days).strftime('%d/%m/%y ') %> </p>
<p>Statut: <span class="badge badge-primary"><%= @invoice.status %></span></p>


<b>Information sur l'entreprise </b><br/><br/>
<p>Adresse: <%= @user.address  %></p>
<p>Banque: <%= @user.bank  %></p>
<p>RIB: <%= @user.bank  %></p>
<p>Siret: <%= @user.siret  %></p>
<p><%= link_to 'Modifier',edit_user_registration_path, class: "btn btn-flat" %>
</p>

  </div>
</div>