config/routes.rb
Rails.application.routes.draw do
  get 'findclients/:client', to: 'invoices#index', as: :findclient
  resources :charges

  get    "invoices/preview/:id",      to: "invoices#preview", as: :preview
  get    "invoices/create_payment/:id",      to: "invoices#create_payment", as: :create_payment
  get    "invoices/new_payment/:id",      to: "invoices#new_payment", as: :new_payment

  resources :labels
  resources :clients
  resources :invoices do
    resources :invoicelines
  end
  resources :materials do
    resources :material_comments
  end
  resources :filters
  resources :folders do
    resources :documents
  end
  devise_for :users
  root to: 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :invoicelines , dependent: :destroy
  def self.search(search)
    if search
      where("name ILIKE ?",  "%#{search}%")
    else
      all
    end
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.search(params[:search])
    @labels = @labels.page(params[:page] || 1)

  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to labels_path, notice: 'Libelle cree' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to labels_path, notice: 'Libelle modifie.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Libelle detruit.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:name, :labeltype, :description, :price)
    end
  end

app/views/labels/_form.html.erb
<%= simple_form_for(@label) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: "Nom du libellé" %>
    <%= f.input :labeltype, collection: [
      "Comptable",
      "Juridique",
      "Social"], label: "Type" %>
    <%= f.input :description %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Soumettre", class: "btn btn-flat" %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<div class="container-list">


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Liste des devis', invoices_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Liste des clients', clients_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Liste des libellés', labels_path, class: 'nav-link' %>
        </li>
      </ul>
      <span class="navbar-text" style="padding-right: 10px;">
        <%= form_tag invoices_path, method: 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Recherche", class: 'btn btn-flat' %>
        <% end %>
      </span>
      <span class="navbar-text">
        <%= link_to 'Nouveau libellé', new_label_path, class: 'btn btn-flat', style: "color: #f4f4f4;" %>
      </span>
    </div>
  </nav>

  <div class="tablehead row" style="margin-top: 20px;">
    <div class="fileimg col-2"></div>
    <div class="info col-2">Nom du libelé</div>
    <div class="info col-2">Type</div>
    <div class="info col-2">Description</div>
    <div class="info col-2">Prix</div>
    <div class="info col-2">Action</div>
  </div>


  <div class="row">
    <% @labels.each do |label| %>
    <div class="document">
      <div class="fileimg col-2">
        <%= link_to label do %>
        <%= image_tag ( "file.png"), class: "image_link" %>
        <% end %>

      </div>
      <div class="info col-2">
        <%= link_to label do %>
        <%= label.name %>
        <% end %>
      </div>
      <div class="info col-2"><%= label.labeltype %></div>
      <div class="info col-2"><%= label.description %></div>
      <div class="info col-2"><%= label.price %></div>
      <div class="info col-2">
        <%= link_to 'Modifier', edit_label_path(label), class: "btn-flat-edit" %>
        <%= link_to 'Supprimer', label, method: :delete, data: { confirm: 'Etes vous certain?' }, class: "btn-flat-edit" %>
      </div>
    </div>
    <% end %>
  </div>

  <%= paginate @labels %>

</div>

app/views/labels/new.html.erb
<div class="container-form">

<%= render 'form', label: @label %>

<%= link_to 'Retour', labels_path %>
</div>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<p>
  <strong>Labeltype:</strong>
  <%= @label.labeltype %>
</p>

<p>
  <strong>Description:</strong>
  <%= @label.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @label.price %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>