config/routes.rb
Rails.application.routes.draw do
  get 'findclients/:client', to: 'invoices#index', as: :findclient
  resources :charges

  get    "invoices/preview/:id",      to: "invoices#preview", as: :preview
  get    "invoices/create_payment/:id",      to: "invoices#create_payment", as: :create_payment
  get    "invoices/new_payment/:id",      to: "invoices#new_payment", as: :new_payment

  resources :labels
  resources :clients
  resources :invoices do
    resources :invoicelines
  end
  resources :materials do
    resources :material_comments
  end
  resources :filters
  resources :folders do
    resources :documents
  end
  devise_for :users
  root to: 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :invoices

  def self.search(search)
    if search
      where("name ILIKE ?",  "%#{search}%")
    else
      all
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.search(params[:search])
    @clients = @clients.page(params[:page] || 1)

end



  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    respond_to do |format|
      if @client.save
        @invoice = Invoice.find(@client.lastinvoice)
        @invoice.client = @client
        @invoice.save
        format.html { redirect_to edit_invoice_path(@client.lastinvoice), notice: 'Client a été ajouté.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    @invoice = Invoice.where(client_id: @client.id).last
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to edit_invoice_path(@invoice), notice: 'Client modifié.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :address, :lastinvoice, :phone, :leader, :email)
    end

  end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.input :name, label: "Nom du client" %>
  <%= f.input :address, label: "Adresse du client" %>
  <%= f.input :phone, label: "Numero de téléphone" %>
  <%= f.input :leader, label: "Nom du dirigeant" %>
  <%= f.input :email, label: "Adresse email du client" %>
</div>

<div class="form-actions">
  <%= f.button :submit, "Soumettre", class: "btn btn-flat" %>
</div>
<% end %>

app/views/clients/edit.html.erb
<div class="container-form">

<%= render 'form', client: @client %>

<%= link_to 'Voir', @client %> |
<%= link_to 'Retour', clients_path %>
</div>

app/views/clients/index.html.erb
<div class="container-list">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Liste des devis', invoices_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Liste des clients', clients_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Liste des libellés', labels_path, class: 'nav-link' %>
        </li>
      </ul>
      <span class="navbar-text" style="padding-right: 10px;">
        <%= form_tag clients_path, method: 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Recherche", class: 'btn btn-flat' %>
        <% end %>
      </span>
      <span class="navbar-text">        <%= link_to 'Nouveau client', new_client_path, class: 'btn btn-flat', style: "color: #f4f4f4;" %>
      </span>

    </div>
  </nav>

  <div class="tablehead row" style="margin-top: 20px;">
    <div class="fileimg col-2"></div>
    <div class="info col-2">Nom</div>
    <div class="info col-2">Adresse</div>
    <div class="info col-2">Dirigeant</div>
    <div class="info col-2">Email</div>
    <div class="info col-2">Action</div>
  </div>

  <div class="row">
    <% @clients.each do |client| %>
    <div class="document">
      <div class="fileimg col-2">
        <%= link_to client do %>
        <%= image_tag ( "file.png"), class: "image_link" %>
        <% end %>

      </div>
      <div class="info col-2">
        <%= link_to client do %>
        <%= client.name %>
        <% end %>
      </div>
      <div class="info col-2"><%= client.address %></div>
      <div class="info col-2"><%= client.leader %></div>
      <div class="info col-2"><%= client.email %></div>
      <div class="info col-2">
        <%= link_to 'Modifier', edit_client_path(client), class: "btn-flat-edit" %>
        <%= link_to 'Supprimer', client, method: :delete, data: { confirm: 'Etes vous certain?' }, class: "btn-flat-edit" %>
      </div>
    </div>
    <% end %>
  </div>
  <%= paginate @clients %>
</div>

app/views/clients/new.html.erb
<div class="container-form">

<%= render 'form', client: @client %>

<%= link_to 'Retour', clients_path %>

</div>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Leader:</strong>
  <%= @client.leader %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>