config/routes.rb
Rails.application.routes.draw do
  get 'findclients/:client', to: 'invoices#index', as: :findclient
  resources :charges

  get    "invoices/preview/:id",      to: "invoices#preview", as: :preview
  get    "invoices/create_payment/:id",      to: "invoices#create_payment", as: :create_payment
  get    "invoices/new_payment/:id",      to: "invoices#new_payment", as: :new_payment

  resources :labels
  resources :clients
  resources :invoices do
    resources :invoicelines
  end
  resources :materials do
    resources :material_comments
  end
  resources :filters
  resources :folders do
    resources :documents
  end
  devise_for :users
  root to: 'invoices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :document, DocumentUploader, mount_on: :document

  belongs_to :folder

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :get_folder

  # GET /documents
  # GET /documents.json
  def index
    @documents = @folder.documents
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    @document.folder = Folder.find(params[:folder_id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.folder = Folder.find(params[:folder_id])

    respond_to do |format|
      if @document.save
        format.html { redirect_to folder_documents_url, notice: 'Document créé avec succès' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to folder_documents_url, notice: 'Document modifié avec succès' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to folder_documents_url, notice: 'Document créé avec succès' }
      format.json { head :no_content }
    end
  end

  private

  def get_folder
    @folder = Folder.find(params[:folder_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:name, :order, :document, :folder_id)
    end
  end

app/views/documents/_form.html.erb
<%= simple_form_for([@folder, @document]) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.input :name, label: 'Nom du document' %>
  <div>
    <%= f.file_field :document %>
  </div>
</div>
<div class="spacer"></div>
<div class="form-actions btn btn-flat">
  <%= f.button :submit, "Ajouter le fichier" %>
</div>
<% end %>

app/views/documents/edit.html.erb
<div class="header">
  <h2>Modifier le document:</h2>
  <h1> <%= @document.name %> de <%= @folder.name %></h1>
  <div class="action">
  <div>
    <%= link_to folder_documents_path do %>
Retour à la liste des documents de <%= @folder.name %>
    <% end %>
  </div>
  <div>

  </div>
</div>

</div>

<div class="container-list">
<%= render 'form', document: @document %>

</div>

app/views/documents/index.html.erb
<div class="header">
  <h2>Consulter les documents de</h2>
  <h1> <%= @folder.name %></h1>
  <div class="action">
  <div> <%= link_to 'Revenir à la liste des dossiers', root_path %></div>
   <% if current_user.superadmin_role? || current_user.supervisor_role? %>
  <%= link_to 'Ajouter un document', new_folder_document_path, class: "btn-flat" %>
  <% end %>
</div>

</div>


<div class="container-list">


  <% @documents.each do |document| %>

      <%= link_to document.document.url do %>
    <div class="notification">
      <img src='https://images.unsplash.com/photo-1471970471555-19d4b113e9ed?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80' class="avatar-large" />
  <div class="notification-content">
      <%= link_to document.document.url do %>
    <p><small><%= document.name %></small>
    <% end %>
  </p>
    <p> <i>Crée le <%= document.created_at %></i> </p>
    <p> <i>Modifié le <%= document.updated_at %></i> </p>
     </div>
  <div class="notification-actions">
  <% if current_user.superadmin_role? || current_user.supervisor_role? %>
  <%= link_to edit_folder_document_path(@folder, document) do %>
    Modifier <i class="fas fa-pencil-alt"></i>
    <% end %>
  <%= link_to [@folder, document], method: :delete, data: { confirm: 'Êtes-vous certain de vouloir supprimer ce fichier?' } do %>
    Supprimer <i class="far fa-trash-alt"></i>
    <% end %>
  <% end %>
  </div>
  <% end %>
  </div>
<% end %>







</div>

app/views/documents/new.html.erb
<div class="header">
  <h2>Joindre un document à:</h2>
  <h1> <%= @folder.name %></h1>
  <div class="action">
  <div>
    <%= link_to folder_documents_path do %>
Retour à la liste des documents de <%= @folder.name %>
    <% end %>
  </div>
  <div>

  </div>
</div>

</div>

<div class="container-list">

<%= render 'form', document: @document %>

</div>

app/views/documents/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @document.order %>
</p>

<p>
  <strong>Document:</strong>
  <%= @document.document %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>